-- ------------------------------------------------------------
-- Trendiv Database Schema (Supabase)
-- ------------------------------------------------------------

-- ============================================================
-- v1: Trend 테이블 (레거시, 운영 중)
-- ============================================================

-- 1. Trend 테이블 확장 (Category 추가)
ALTER TABLE trend
ADD COLUMN IF NOT EXISTS category text;

-- 2. 성능 최적화를 위한 인덱스
CREATE INDEX IF NOT EXISTS idx_trend_source ON trend(source);
CREATE INDEX IF NOT EXISTS idx_trend_category ON trend(category);

-- 3. (참고) Trend 테이블 기본 스키마
-- create table public.trend (
--   id bigint generated by default as identity,
--   created_at timestamp with time zone not null default now(),
--   title text null,
--   link text not null,
--   date text null,
--   source text null,
--   status text null default 'RAW'::text,
--   analysis_results jsonb[] null,
--   category text null,
--   content_raw text null,
--   content text null,
--   represent_result jsonb null,
--   constraint trend_pkey primary key (id),
--   constraint trend_link_key unique (link)
-- ) tablespace pg_default;


-- ============================================================
-- v2: Article 테이블 마이그레이션
-- trend 테이블을 대체하며 report_html 컬럼이 추가됨
-- ============================================================

-- STEP 1: article 테이블 생성
CREATE TABLE IF NOT EXISTS public.article (
  id               bigint generated by default as identity,
  created_at       timestamp with time zone not null default now(),
  title            text null,
  link             text not null,
  date             text null,
  source           text null,
  category         text null,
  status           text null default 'RAW'::text,
  content_raw      text null,
  content          text null,
  analysis_results jsonb[] null,
  represent_result jsonb null,
  report_html      text null,  -- AI 생성 HTML 보고서 (v2 신규)
  constraint article_pkey primary key (id),
  constraint article_link_key unique (link)
) tablespace pg_default;

-- STEP 2: 인덱스
CREATE INDEX IF NOT EXISTS idx_article_source    ON article(source);
CREATE INDEX IF NOT EXISTS idx_article_category  ON article(category);
CREATE INDEX IF NOT EXISTS idx_article_status    ON article(status);
-- report_html 없는 ANALYZED 아티클 빠른 조회용 (리포트 생성 크론)
CREATE INDEX IF NOT EXISTS idx_article_no_report ON article(id)
  WHERE status = 'ANALYZED' AND report_html IS NULL;

-- STEP 3: trend → article 데이터 이관
-- ⚠️ article 테이블이 비어있을 때만 실행할 것
-- analysis_results: trend 테이블은 jsonb, article은 jsonb[] → ARRAY[]로 캐스팅
INSERT INTO public.article (
  id, created_at, title, link, date, source, category,
  status, content_raw, content, analysis_results, represent_result
)
SELECT
  id, created_at, title, link, date, source, category,
  status, content_raw, content,
  CASE
    WHEN analysis_results IS NULL THEN NULL
    ELSE ARRAY(SELECT jsonb_array_elements(analysis_results))
  END,
  represent_result
FROM public.trend
ON CONFLICT (link) DO NOTHING;

-- STEP 4: identity 시퀀스를 이관된 데이터의 max(id)로 맞추기
-- (새 레코드 삽입 시 id 충돌 방지)
SELECT setval(
  pg_get_serial_sequence('article', 'id'),
  COALESCE((SELECT MAX(id) FROM article), 1)
);

-- ============================================================
-- v2 안정화 후: trend 테이블 삭제 (충분히 검증 후 실행)
-- ============================================================
-- DROP TABLE IF EXISTS public.trend;
